name: wlci-species
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7.3
  - joblib
  - jsonschema
  - jupyter
  - pandas
  - pip
  - requests
  - pyzotero
  - pip:
    - sciencebasepy
    - git+git://github.com/usgs-bcb/bispy.git


